import Head from "next/head";
import Header from "../components/Header";
import axios from "axios";
import View from "../components/View";
import PageNav from "../components/PageNav";
import Categories from "../components/Categories";

export default function Home({ data, page }) {
  return (
    <div className="bg-white">
      <Head>
        <title>Flixo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Categories data={data} />
      <View movies={data} />
      <PageNav page={page} />
    </div>
  );
}

export async function getServerSideProps({
  query: { page = 1, category = "netflix" },
}) {
  const baseUrl = "https://flixon.herokuapp.com/api/movies";

  const response = await axios.get(
    `${baseUrl}/?category=${category}&page=${page}`
  );
  return {
    props: {
      data: response.data,
      page: parseInt(page, 10),
    },
  };
}
