import Head from "next/head";
import Header from "../components/Header";
import axios from "axios";
import View from "../components/View";
import PageNav from "../components/PageNav";
import Categories from "../components/Categories";
import Script from "next/script";
import { useState } from "react";

export default function Home({ data, page }) {
  return (
    <div className="bg-white">
      <Head>
        <title>Flixon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Categories data={data} />
      <View movies={data} />
      <PageNav page={page} />
    </div>
  );
}

export async function getServerSideProps({
  query: { page = 1, category = "" },
}) {
  const baseUrl = process.env.BASE_URL;
  const response = await axios.get(
    `${baseUrl}/?category=${category
      .toLowerCase()
      .replace(/ /g, "-")}&page=${page}`
  );
  return {
    props: {
      data: response.data,
      page: parseInt(page, 10),
    },
  };
}
